# Indexing with logical vectors (Boolean Arrays)

In [1]:
import numpy as np
a = np.array([1, 0, -2, 3])
a > 0  # this is a logical vector (Boolean Arrays)

array([ True, False, False,  True])

**Boolean Arrays as Masks:**  A powerful pattern is to use Boolean arrays as masks, to select particular subsets of the data themselves. Suppose we want an array of all values in the array that are larger than 0:

In [2]:
a[a > 0]  #returns those elements of a where a > 0 is true

array([1, 3])

Returned is a one-dimensional array filled with all the values that meet this condition; in other words, all the values in positions at which the mask array is True.

**Exercise:** Shorten a vector by removing the zero elements

In [3]:
a = np.array([1, 0, -2, 3])
a = a[a!=0]
a

array([ 1, -2,  3])

**Exercise:** Shorten a vector by removing its largest and smallest elements

In [4]:
a = np.array([2, 1, -2, 0, -2, 3])
a = a[(a < np.max(a)) & (a > np.min(a))]
a

array([2, 1, 0])

Logical vectors may also be defined directly:

A boolean array can be created manually by using dtype=bool when creating the array. Values other than 0, None, False or empty strings are considered True.

In [5]:
a = np.array([1, 0, -2, 3])
bool_arr = np.array([0, 1, 1, False], dtype=bool)
print(bool_arr)
a[bool_arr]

[False  True  True False]


array([ 0, -2])

# Functions of logical vectors
The Numpy equivalents of the logical classifiers are
$$
\begin{align}
np.any(a) & \Leftrightarrow \exists k: a_k \ne 0 \\
np.all(a) & \Leftrightarrow \forall k: a_k \ne 0
\end{align}
$$

In [6]:
a = np.array([1, 0, -2, 3])
a.any() # or np.any(a)

True

In [7]:
a.all() # or np.all(a)

False

**Exercise:** How can you test if two vectors are the same?

You can do an element-wise comparison of the two arrays, followed by the logical classifier all:

In [8]:
a = np.array([1, 0, -2, 3])
b = np.array([0, 0, -2, 3])
print(a == b)
(a == b).all()  # or np.all(a == b)

[False  True  True  True]


False

... and how if they are different?

In [9]:
print(a != b)
(a != b).any()  # or np.any(a != b)

[ True False False False]


True

The function where returns all indices of a vector whose elements are nonzero:

In [10]:
a = np.array([1, 0, -2, 3])
np.where(a)

(array([0, 2, 3]),)

In [11]:
a.nonzero()

(array([0, 2, 3]),)

and now we remove them:

In [12]:
a[np.where(a)[0]]  # same as a = a[a!=0]

array([ 1, -2,  3])

The functions isnan and isinf return logical vectors indicating the elements that are  or undefined (NaN):

In [13]:
a = np.array([1, 0, -2, 3])

import warnings
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    b = a/0
    
print(b)
np.isnan(b)

[ inf  nan -inf  inf]


array([False,  True, False, False])

In [14]:
np.isinf(b)

array([ True, False,  True,  True])

This can be used to remove unwanted NaNs:

In [15]:
b[~np.isnan(b)]

array([ inf, -inf,  inf])

# Elements of programming
## Conditional statements: if

In the If statement the code is executed based on whether it meets the specified condition. It has a code body that only executes if the condition in the if statement is true. The statement can be a single line or a block of code:

In [16]:
a = -5
b = 0

if a < 0:
    b = -a

b

5

In [17]:
a = 5
b = 0

if a < 0:
    b = -a

b

0

**If Else** is used when both the true and false parts of a given condition are specified to be executed. When the condition is true, the statement inside the if block is executed; if the condition is false, the statement outside the if block is executed:

In [18]:
a = 5
b = 0

if a < 0:
    b = -a
else:
    b = a
b

5

One may add any number of explicit alternatives with conditions using **elseif** and a final alternative using else. Note else must always appear as the last statement and always goes without a condition.

In [19]:
a = 0
b = 0

if a < 0:
    b = -a
elif a==0:
    b = float("NaN")
else:
    b = a
b

nan

**Exercise:** Write a function tiered_interest that accepts an initial balance b and returns the new balance after one year if the annual interest rate p is tiered: 
$$
p = \begin{cases} 
      3\%, & b\leq 10000 \\
      2\%, & 10000 < b\leq 50000 \\
      1\%, & b>50000 
   \end{cases}
$$

In [20]:
def tiered_interest(b):
    """
    TIERED_INTEREST computes new balance given initial balance b using tiered interest rat"
    """
    if b <= 10000:
        p = 0.03
    elif b <= 50000:
        p = 0.02
    else:
        p = 0.01
    return b*(1 + p)
tiered_interest(2000)
tiered_interest(20000)
tiered_interest(200000)

2060.0

20400.0

202000.0

Does this function still work if $b$ is a vector of balances (e.g. several customers of a bank)? Write a modified function tiered_interest2 for this case.

In [21]:
def tiered_interest2(b):
    """
    TIERED_INTEREST computes new balance given initial balance b, 
    which may be a vector, using tiered interest rate
    """
    return b + 0.03*b*(b <= 10000) + 0.02*b*((b > 10000) & (b <= 50000)) + 0.01*b*(b > 50000)
tiered_interest2(b)

nan

## Several alternatives: switch

Let's throw a dice and depending on the result do different things.

Before Python 3.10 here a solution with dictionary

In [22]:
d = np.random.randint(1, 7)  # draw number

# define the function blocks
def one():
    print('*')

def two():
    print('**')

def three():
    print('***')

def more():
    print('more than 3')

# map the inputs to the function blocks
options = {1 : one,
           2 : two,
           3 : three,
           4 : more,
           5 : more,
           6 : more
}

options[d]()

***


In Python 3.10, they introduced the [pattern matching](https://docs.python.org/3.10/whatsnew/3.10.html#pep-634-structural-pattern-matching):

## Recursion

A typical example of a recursive definition is the factorial of an integer n:

$$
n! = \begin{cases} 
      1, & n=0 \\
      n(n-1)!, & n>0
   \end{cases}
$$

Python functions can call themselves, see the implementation in 'recur_factorial'. Care must be taken to avoid an infinite recursion! This occurs if n is not an integer or negative.

In [23]:
# Factorial of a number using recursion

def recur_factorial(n):
   if n == 1:
       return n
   else:
       return n*recur_factorial(n-1)

num = 7

# check if the number is negative
if num < 0:
   print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
   print("The factorial of 0 is 1")
else:
   print("The factorial of", num, "is", recur_factorial(num))



The factorial of 7 is 5040


### Loops: for

for loops are used for predetermined repitition and have the general form

In [24]:
for x in range(6):
  print(x)

0
1
2
3
4
5


In [25]:
for x in range(1,6,2):
  print(x)

1
3
5


In [26]:
for x in [1.1, 4.4, 2, 7.5]:
  print(x)

1.1
4.4
2
7.5


Or all in one line:

List comprehensions are lists that generate themselves with an internal for loop. They’re a very common feature in Python and they look something like:

[thing for thing in list_of_things]

In [27]:
[print(x) for x in [1.1, 4.4, 2, 7.5]]


1.1
4.4
2
7.5


[None, None, None, None]

In [28]:
[x**2 for x in [1.1, 4.4, 2, 7.5]]

[1.2100000000000002, 19.360000000000003, 4, 56.25]

**Exercise:** Write a function fact2 that implements the factorial using a for loop based on the expression 

$$n!=\prod_{k=1}^n k$$

In [29]:
import math
def fact2(n):
    """
    FACT2 computes n! using a for loop
    """
    if math.floor(n) != abs(n):
        raise ValueError('Argument must be positive integer!')
    
    f = 1
    for k in range(2,n+1):
        f = f*k
        
    return f

fact2(7)

5040