# Homework 3
The linear system of equations is given
\begin{eqnarray*}
    x - 2y + 3 z &=& 1\\
    2x + 3y + z &=& -3\\
    -3x + y - 2z &=& 4
\end{eqnarray*}
Build the expanded coefficient matrix and apply the
Gaussian elimination method by using Python
line transformations on the matrix.
Get the solution of the linear system of equations.

Compare with the solution you will get if you solve the
linear system of equations with Python using the np.linalg.solve function.

In [1]:
import numpy as np

A = np.array([[1, -2, 3], [2, 3, 1], [-3, 1, -2]])
b = np.array([1, -3, 4])

## direct solution

In [2]:
x = np.linalg.solve(A,b)
x

array([-2.00000000e+00, -6.05576195e-17,  1.00000000e+00])

## Gaussian elimination
### extended coefficient matrix

np.r_[ ... ] and np.c_[ ... ] are useful alternatives to vstack and hstack, with square brackets [] instead of round ().

In [3]:
Ab = np.c_[ A, b ] 
Ab

array([[ 1, -2,  3,  1],
       [ 2,  3,  1, -3],
       [-3,  1, -2,  4]])

### row canonical form
transform to row canonical form (Zeilenstufenform)

In [4]:
Ab[1,:] = Ab[1,:] - Ab[1,0]/Ab[0,0]*Ab[0,:]
Ab[2,:] = Ab[2,:] - Ab[2,0]/Ab[0,0]*Ab[0,:]
Ab[2,:] = Ab[2,:] - Ab[2,1]/Ab[1,1]*Ab[1,:]
Ab

array([[ 1, -2,  3,  1],
       [ 0,  7, -5, -5],
       [ 0,  0,  3,  3]])

In [5]:
from sympy import Matrix
m = Matrix(Ab)
M_rref = m.rref()
print("The Row echelon form of matrix M and the pivot columns : {}".format(M_rref))

The Row echelon form of matrix M and the pivot columns : (Matrix([
[1, 0, 0, -2],
[0, 1, 0,  0],
[0, 0, 1,  1]]), (0, 1, 2))


### back substitution

In [6]:
x[2] = Ab[2,3]/Ab[2,2]
x[1] = (Ab[1,3] - x[2]*Ab[1,2])/Ab[1,1];
x[0] = (Ab[0,3] - x[1]*Ab[0,1] - x[2]*Ab[0,2])/Ab[0,0]
x

array([-2.,  0.,  1.])