# Homework 2
Write a function that rotates a vector in $R^2$ by a given angle. The arguments of the function should be the vector and the angle in degrees, and the function should return the rotated vector. Use the matrix product.

## Rotation Matrix

The new coordinates $(x′, y′)$ of a point $(x, y)$ after rotation are

$$\begin{aligned}x'&=x\cos \theta -y\sin \theta \,\\y'&=x\sin \theta +y\cos \theta \,\end{aligned}.$$

Those, the two dimensional rotation matrix which rotates points in the $xy$ plane anti-clockwise through an angle $\theta$ about the origin is

$$R=\left[ {\begin{array}{cc}
   \cos {\theta} & -\sin {\theta} \\
   \sin {\theta} & \cos {\theta} \\
  \end{array} } \right].$$
  
To create a rotation matrix as a NumPy array for $\theta=30$, it is simplest to initialize it with as follows:

In [1]:
theta = np.radians(30)
c, s = np.cos(theta), np.sin(theta)
R = np.array(((c, -s), (s, c)))
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

Derivation: https://scipython.com/book/chapter-6-numpy/examples/creating-a-rotation-matrix-in-numpy/

## Vector

In [2]:
v = np.array((0,1))
v

array([0, 1])

### apply the rotation matrix $R$ to $v$

In [3]:
R.dot(v)

array([-0.5      ,  0.8660254])

### Now as function

In [4]:
def rotate(v,theta_deg):
    """
    ROTATE rotates the two-dimensional vector v by the angle theta in
    degrees and returns the result.
    """
    theta = np.radians(theta_deg)
    c, s = np.cos(theta), np.sin(theta)
    R = np.array(((c, -s), (s, c)))
    return R.dot(v)

rotate(np.array((0,1)),45)   

array([-0.70710678,  0.70710678])